export const DEFAULT_TICKERS = [
  { symbol: "NVDA", name: "NVIDIA Corp.", asset_type: "stocks" },
  { symbol: "AAPL", name: "Apple Inc.", asset_type: "stocks" },
  { symbol: "GOOGL", name: "Alphabet Inc.", asset_type: "stocks" },
  { symbol: "AMZN", name: "Amazon.com Inc", asset_type: "stocks" },
  { symbol: "META", name: "Meta Platforms, Inc.", asset_type: "stocks" },
  { symbol: "MSFT", name: "Microsoft Corporation", asset_type: "stocks" },
  { symbol: "TSLA", name: "Tesla Inc.", asset_type: "stocks" },
  { symbol: "AVGO", name: "Broadcom Inc.", asset_type: "stocks" },
  { symbol: "INTC", name: "Intel Corp.", asset_type: "stocks" },
  { symbol: "NFLX", name: "Netflix Inc.", asset_type: "stocks" },
  { symbol: "BTC/USD", name: "Bitcoin USD", asset_type: "crypto" },
  { symbol: "ETH/USD", name: "Ethereum USD", asset_type: "crypto" },
  { symbol: "XRP/USD", name: "XRP USD", asset_type: "crypto" },
  { symbol: "SOL/USD", name: "Solana USD", asset_type: "crypto" },
  { symbol: "LINK/USD", name: "Chainlink USD", asset_type: "crypto" },
  { symbol: "DOGE/USD", name: "Dogecoin USD", asset_type: "crypto" },
  { symbol: "DOT/USD", name: "Polkadot USD", asset_type: "crypto" },
  { symbol: "SHIB/USD", name: "Shiba Inu USD", asset_type: "crypto" },
  { symbol: "PEPE/USD", name: "Pepe USD", asset_type: "crypto" },
  { symbol: "AVAX/USD", name: "Avalanche USD", asset_type: "crypto" },
];
